spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:file:~/testdb;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
